### ISSUE TITLE
SP variables are unsupported in FOR SYSTEM_TIME expression

### ISSUE THREAD

**Issue by alvinr** [tempesta-tech/mariadb#106]
# Problem
It appears that the Parser for Stored Procedures does not accept the `for system_time` extension for a select statement.

# Solution
Support `for system_time` in queries in stored procedures.

# Reproduce
```sql
DELIMITER //

CREATE PROCEDURE dept_salary_when (IN for_when TIMESTAMP, OUT wage_bill INT)
 BEGIN
  SELECT sum(salary) INTO wage_bill FROM emp
  FOR SYSTEM_TIME AS OF for_when
  ;
 END;
//

DELIMITER ;

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'for_when

```

**Comment by midenok** [comment]
It's not whole `for system_time` unsupported in SP, just SP variable in `for system_time`.

**Comment by midenok** [comment]
`TIMESTAMP` keyword is missing in original code. This code seems to succeed:

```sql
delimiter //

create or replace procedure dept_salary_when (in for_when timestamp, out wage_bill int)
 begin
  select sum(salary) into wage_bill from emp
  for system_time as of TIMESTAMP for_when
  ;
 end;
//

delimiter ;
```

**Comment by alvinr** [comment]
@midenok good catch, did not see the missing `TIMESTAMP` clause.

**Comment by midenok** [comment]
@alvinr I want to make this `TIMESTAMP` keyword optional default because don't see much help from it.  Do you mind?
