### ISSUE TITLE
Rebase onto 10.3

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#109]

**Comment by kevgs** [comment]
10.2: 143d512a2202dbd320ec9b9e37dafc36fc2b36d8

Failing test(s): connect.index connect.mrr connect.mysql_index tokudb.card_auto_analyze_lots mroonga/storage.index_multiple_column_unique_datetime_index_read tokudb.i_s_tokudb_lock_waits_timeout tokudb.i_s_tokudb_locks tokudb.i_s_tokudb_trx tokudb_bugs.db397_delete_trigger tokudb_bugs.db397_insert_trigger tokudb_bugs.db397_update_trigger tokudb_bugs.db945 tokudb_bugs.tokudb718 archive.archive-big

**Comment by midenok** [comment]
Please, create branch `ek/109_rebase` from b53491270468e3af04e36b47a87a437798c07939 and try to rebase onto 10.3. Your previously resolved conflicts should replay automatically.

**Comment by midenok** [comment]
Merge latest commits from `trunk`, save `natsys/trunk` to `ek/old_trunk` and replace `natsys/trunk` with `ek/109_rebase`. Don't forget to update `natsys/base`. There must be no test failures in `natsys/trunk`. Thanks!

**Comment by midenok** [comment]
Please, list here tests that you will disable.

**Comment by kevgs** [comment]
Disabled tests that fail in both ek/109_rebase and 10.3:
```
encryption.innodb_lotoftables
innodb_zip.wl6501_1
innodb_zip.wl6501_crash_3
tokudb_parts.partition_alter1_1_2_tokudb
tokudb_parts.partition_alter1_1_tokudb
tokudb_parts.partition_alter1_2_tokudb
tokudb_parts.partition_alter2_1_1_tokudb
tokudb_parts.partition_alter2_1_2_tokudb
tokudb_parts.partition_alter2_2_1_tokudb
tokudb_parts.partition_alter2_2_2_tokudb
tokudb_parts.partition_alter4_tokudb
tokudb_parts.partition_basic_tokudb
tokudb_parts.partition_debug_tokudb
tokudb_parts.part_supported_sql_func_tokudb
tokudb.rows-32m-rand-insert
tokudb.rows-32m-seq-insert
```
This test faisl in Jenkins and is disabled in Jenkins config:
```
encryption.innodb_encryption_discard_import
```

**Comment by kevgs** [comment]
`natsys/trunk` and `natsys/base` have changed!

**Comment by midenok** [comment]
Is the issue closed?

**Comment by kevgs** [comment]
This tests fails in Jenkins: `encryption.create_or_replace`. Adding to Jenkins test exclude list.
main.gis fails because of https://github.com/natsys/mariadb_10.2/issues/119

Apart from that all is fine.
