### ISSUE TITLE
Enhancement: "truncate ... before"

### ISSUE THREAD

**Issue by alvinr** [tempesta-tech/mariadb#111]
# Feature request
Extend the "truncate" command to provide a "before" option, e.g.

```
truncate emp for system_time timestamp before "2017-01-04 17:44:27.538087";
```

This is simply a short cut of

```
truncate emp for system_time timestamp between "1970-01-01 00:00:01.000000" and  "2017-01-04 17:44:27.538087";
```

# Rationale
Ease of use. Spec V1.2 also mentions the following

```
TRUNCATE TABLE employee WITH SYSTEM VERSIONING BEFORE TIMESTAMP '2016-02-06 10:03:03';
```

**Comment by kevgs** [comment]
Design: command removes all rows with sys_trx_end less than parameter, do not works with SELECT.
