### ISSUE TITLE
Enhancement: Global/Session System Time

### ISSUE THREAD

**Issue by alvinr** [tempesta-tech/mariadb#117]
# Problem
An application cannot utilize the features of Temporal queries without having to re-write each SELECT statement in the application to add System Time into the FROM clause etc. This has implications of ORM and other frameworks that the Application may be using.

In order to ease the uptake of this feature, historic data could be projected through the existing queries *if* there is a mechanism to define the System Time that all queries should execute against.

MariaDB already has the concept of Session & Global variables:
```
SET variable_assignment [, variable_assignment] ...

variable_assignment:
      user_var_name = expr
    | [GLOBAL | SESSION] system_var_name = expr
    | [@@global. | @@session. | @@]system_var_name = expr
```

https://mariadb.com/kb/en/mariadb/set/

# Proposal
Add additional system variable to support the timeframe for queries, e.g.
- `temporal_current_timestamp = ' 2011-05-17-14.45.31.434235000000'`
- `temporal_current_timestamp = 'all'`

Variable names approved by Monty/Sergei.

The timespan defined by the above variables is applied to all subsequent queries implicitly, governed by the scope of the variable (i.e. GLOBAL vs. SESSION).

# Not In Scope
- No support for Transaction ID's via this syntax
  - Oracle supports with `DBMS_FLASHBACK.ENABLE_AT_SYSTEM_CHANGE_NUMBER (10280403339);`
  - DB2 does not support
  - SQL Server does not support
- No support for `between` via this syntax
  - Oracle, DB2 and SQL Server do not support this

Both could be a requirement down the road, but from a competitive or usage aspects, we can live without both in the initial phase.

# Rational
- Make it easier to use this feature without modification to the applications queries, ORMs etc.
- Competitive
  - Oracle `DBMS_FLASHBACK.ENABLE_AT_TIME ('13-SEP-04 08:10:58');`
  - DB2 `SET CURRENT TEMPORAL SYSTEM_TIME = TIMESTAMP '2011-02-28-09.10.12.649592000000';`
  - SQL Server does not support

**Comment by midenok** [comment]
I see only one variable `temporal_current_timestamp`. Are there other variables that were approved?

**Comment by alvinr** [comment]
@midenok this is a proposal - needs to be validate sand approved. The proposal is for a Single variable at this time, see "Not In Scope" section.

**Comment by midenok** [comment]
The proposal tells about variables in plural, so I thought there was a typo.

**Comment by alvinr** [comment]
@midenok corrected to remove the plural from the spec.

**Comment by midenok** [comment]
set_system_variable
class set_var
class sys_var
MYSQL_SYSVAR_STR

**Comment by midenok** [comment]
Sysvar should also be *session*. Renamed to **vers_current_time**.

**Comment by midenok** [comment]
#### Item created from `set global`:
```
#0 Item::Item (this=0x7fffec7e6168, thd=0x7fffec3e6070) at /home/midenok/src/mariadb/midenok/src/sql/item.cc:477
#1 0x0000555555a3e527 in Item_basic_value::Item_basic_value (this=0x7fffec7e6168, thd=0x7fffec3e6070) at /home/midenok/src/mariadb/midenok/src/sql/item.h:1866
#2 0x0000555555a3e72f in Item_basic_constant::Item_basic_constant (this=0x7fffec7e6168, thd=0x7fffec3e6070) at /home/midenok/src/mariadb/midenok/src/sql/item.h:1903
#3 0x0000555555a88228 in Item_string::Item_string (this=0x7fffec7e6168, thd=0x7fffec3e6070, str=0x7fffec7e6160 "1-1-1", length=5, cs=0x555557093160 <my_charset_utf8_general_ci>, dv=DERIVATION_COERCIBLE, repertoire=1) at /home/midenok/src/mariadb/midenok/src/sql/item.h:3023
#4 0x0000555555d05831 in MYSQLparse (thd=0x7fffec3e6070) at /home/midenok/src/mariadb/midenok/src/sql/sql_yacc.yy:13991
#5 0x0000555555b11425 in parse_sql (thd=0x7fffec3e6070, parser_state=0x7ffff7f53670, creation_ctx=0x0, do_pfs_digest=true) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:9854
#6 0x0000555555b0c5ea in mysql_parse (thd=0x7fffec3e6070, rawbuf=0x7fffec7e6088 "set global vers_current_time='1-1-1'", length=36, parser_state=0x7ffff7f53670, is_com_multi=false, is_next_command=false) at /home/midenok/src/mariadb/midenok/src/sql/sql_parse.cc:7797
```
