### ISSUE TITLE
VTMD InnoDB system table

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#122]
InnoDB system table analogous to VTQ. Information schema for table for tracking data and debug. Table structure is described [here](https://github.com/tempesta-tech/mariadb_10.2/wiki/DDL-Survival#vtd-structure).

**Comment by midenok** [comment]
Add list of all failed tests here.

**Comment by kevgs** [comment]
archive.mysqlhotcopy_archive main.mysqlhotcopy_myisam main.information_schema_inno binlog.binlog_unsafe plugins.server_audit plugins.thread_pool_server_audit plugins.two_password_validations plugins.cracklib_password_check encryption.encrypt_and_grep
