### ISSUE TITLE
Copy tables and history

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#132]
Currently there is no ability to copy table "as is". Commands that should create versioned table:
```sql
create table t2 like t1;
create table t2 select * from t1 for system_time all;
replace into t2 select * from t1 for system_time all;
insert into t2 select * from t1 for system_time all;
```

Currently these commands work without special treatment of versioned `t1`.

**Comment by midenok** [comment]
Related to #82.

**Comment by kevgs** [comment]
Partially implemented in https://github.com/tempesta-tech/mariadb_10.2/commit/4a85e685bdad2e84bb4e9cc62d21ece1424582fe
