### ISSUE TITLE
Improvements for implicitly GENERATED fields

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#135]
Currently implicit fields are named `sys_trx_start`, `sys_trx_end`. There should be ability to define arbitrary default names for them.

Column names should be mutated by prefixing `_` to both sys fields in case of name clash with existing columns until there will be no clash. 

In `alter.test`:
Test adding system versioning when a table already has `sys_trx_start` column, say, INT or VARCHAR.

**Comment by vuvova** [comment]
I don't think you need to bother implementing configurable default names. We have automatic generated names for indexes, foreign keys, check constraints — none of them are configurable. The user either specifies a name in `CREATE TABLE` or she doesn't, and then the server automatically picks up a non-conflicting name (e.g. with _1, _2, etc suffixes).

I'd suggest to be consistent here and follow existing behavior.

**Comment by midenok** [comment]
It may perfectly keep consistency with existing behaviour if f.ex. variable is not set. It would be good for me to have control of these names to spare some typing.

**Comment by vuvova** [comment]
if the whole purpose of this variable is to save you some typing, then you can add a variable only in debug mode. Or add it, and at the very end of the project remove it and search-replace tests to use longer name (I've did something like that a couple of times).

**Comment by vuvova** [comment]
Please, no "mutation". First, it does not belong to system versioning feature, these fields are simply created SYSTEM_INVISIBLE and they exhibit all behavior of SYSTEM_INVISIBLE fields.

Second, SYSTEM_INVISIBLE fields have *well defined* documented names (like ROWID), they are not renamed automatically (otherwise they'd be rather difficult to find and use).

**Comment by midenok** [comment]
Too many reserved names leave less freedom for application. This may be especially important for **transparent versioning** mode. DBMS is system that serves application needs, but not vice versa. But this is not critical and may be postponed until real request.
