### ISSUE TITLE
Versioned unique key

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#140]
For SELECT over time ranges, records with duplicate unique-key values show different versions of the same record. This is like UNION ALL works. Unique indexes and a primary keys are no longer unique. One needs to take care to tell the optimizer that these indexes are not unique.

**Comment by kevgs** [comment]
`row_start/row_end` is prohibited inside `UNIQUE|PRIMARY KEY` by standard in `11.7 <unique constraint definition>`. Constrains should be evaluated for `t for system_time as of current_timestamp`.
