### ISSUE TITLE
Full test failures

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#155]
Full test fails on following tests:
```
rpl.rpl_delayed_slave
innodb.innodb_defrag_concurrent
encryption.innodb_encryption_discard_import
tokudb.bf_delete
```
Pls, check if any of them is related to late (as of #144) bug fixes.

**Comment by kevgs** [comment]
These tests work at my laptop. But they require much time to pass. Probably, it's a cause of failure at testing server.
