### ISSUE TITLE
Improve vtq_query_commit_ts() algorithm.

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#168]
`vtq_query_commit_ts()` queries `VTQ` by `commit_ts` Several rows with the same timestamp can exist. And currently function returns first encountered. Instead of that it should return a row with min or max (based on `backwards` argument) `trx_id` to match algorithms from [here](https://github.com/tempesta-tech/mariadb_10.2/wiki/Ordering-of-transactions)

> If there are multiple VTQ records at COMMIT_TS0, then select one corresponding to max(COMMIT_ID).

**Comment by midenok** [comment]
Description?
