### ISSUE TITLE
Enable FOR SYSTEM_TIME BEFORE for SELECT

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#170]
I don't see any trouble of enabling such kind of query:

```sql
select * from t0 for system_time before timestamp '1990-01-01';
```

It will help to check what TRUNCATE ... BEFORE will delete. If there any objections to enable it, please state them here.

Also it should work with `TRANSACTION` selector:

```sql
select * from t0 for system_time before transaction 11012 ;
```

**Comment by kevgs** [comment]
> It will help to check what TRUNCATE ... BEFORE will delete. If there any objections to enable it, please state them here.

I have no objections. It's really useful to see what's gonna be deleted.
