### ISSUE TITLE
More tests on TravicCI

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#191]
1) debug + versioning + valgrind
2) debug + versioning
3) release + all_suites + -DBUILD_CONFIG=mysql_release (will be split on about 3 parts)

**Comment by kevgs** [comment]
`-DBUILD_CONFIG=mysql_release` results in a `cmake` error
```
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find GnuTLS: Found unsuitable version "2.12.23", but required is
  at least "3.3.24" (found /usr/lib/x86_64-linux-gnu/libgnutls.so)
```

Do we really need that flag?
@midenok

**Comment by midenok** [comment]
Is there bug report on MDEV?

**Comment by kevgs** [comment]
https://github.com/MariaDB/mariadb-connector-c/commit/cae391f7bf47f17fb246cded8ddf0ef19dbfbdec

https://jira.mariadb.org/browse/CONC-207?jql=text%20~%20"gnutls"

**Comment by kevgs** [comment]
It's only 3.2.11 on Ubuntu 14.04 http://packages.ubuntu.com/trusty/libs/

**Comment by midenok** [comment]
This  is minor priority.
