### ISSUE TITLE
Tests failing in Travis CI

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#194]
archive.mysqlhotcopy_archive
main.mysqlhotcopy_myisam
main.information_schema_inno
binlog.binlog_unsafe
plugins.server_audit
plugins.thread_pool_server_audit
plugins.two_password_validations
plugins.cracklib_password_check
encryption.encrypt_and_grep

Need to disable it from test.

**Comment by kevgs** [comment]
Added a file with disabled tests https://github.com/tempesta-tech/mariadb/commit/bd70346a95ac66ca5eb1aa7dcc1f62580d2a2f64

**Comment by midenok** [comment]
There should be special branch for *more tests* testing, f.ex. `natsys/nightly`. *Sunny* may copy `natsys/trunk` to `natsys/nightly` on daily basis.

**Comment by kevgs** [comment]
Dedicated Travis is not used anymore.

**Comment by midenok** [comment]
It should be used. It should be merged into MariaDB config and depending on current repo load our versioning config.

**Comment by kevgs** [comment]
Well, it would be good to add `versioning` suite somewhere [here](https://github.com/MariaDB/server/blob/10.3/.travis.yml#L30).
What else you'd suggest?
