### ISSUE TITLE
Timestamp-based versioning for InnoDB

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#209]
##### InnoDB tables should:
1. have possibility to be versioned on SQL level, like MyISAM tables (this issue);
2. mimic timestamp-based versioning, working internally on TRX_ID basis (not subjected in current issue).

**Comment by vuvova** [comment]
Why would you need 1? Does it have any benefits compared to a true trx_id based versioning?

**Comment by midenok** [comment]
Performance. Extra access to VTQ may have serious impact. Reliability. No extra reference layer means less chances to lose data. Simplicity. No need to backup VTQ table on table backup (also solved by **2**). Strategy. Easily implemented **1** may go to 1.0 and collect feedback from users. This may add to vision of whether **2** is needed or to any other aspects of TRX_ID based versioning.

**Comment by vuvova** [comment]
Performance is a good reason. But it needs benchmarking to back it up. (I presume the implementation is trivial, almost like removing one flag from innodb's table flags?)

I don't quite understand Reliability part, need to finish reading the code first.

Simplicity is questionable, it's another option for users to remember and a setting to configure. MariaDB has already way way too much configurable settings.

Strategy — I don't know if I agree with that, if there're no other compelling reasons, nobody will use it and there will be no feedback. Performance is the main thing here.

**Comment by midenok** [comment]
> I don't quite understand Reliability part, need to finish reading the code first.

There is no need to read code. If you have 2 eggs then you have double chance to get one broken.

> Simplicity is questionable, it's another option for users to remember and a setting to configure. MariaDB has already way way too much configurable settings.

No one remembers settings. This is what is copied from manual. Option to remember like 'it can do such and such'? What a big deal... In fact this is pro for software! MariaDB is composite software, we hardly should bother of total number of settings for it. The more parts it gets, the more settings it will have. I believe, System Versioning may have couple of dozens of them. F.ex. as a user I am always glad to have more control over software and very disappointed by modern tendency of 'one-button' interfaces. The other question is what the defaults are. Unix have nasty habit to supply awkward defaults.

**Comment by midenok** [comment]
Current status:
```
Completed: Failed 13/44 tests, 70.45% were successful.

Failing test(s): versioning.replace versioning.alter versioning.select_sp versioning.simple versioning.foreign versioning.cte versioning.insert versioning.update
```

**Comment by midenok** [comment]
Current status:
```
Failing test(s): versioning.replace versioning.select_sp versioning.cte versioning.simple versioning.foreign
```
