### ISSUE TITLE
Excluding XtraDB (from build and tests)

### ISSUE THREAD

**Issue by avodaniel** [tempesta-tech/mariadb#21]
I have two issues here:

1) How to build MariaDB without XtraDB. It seems that any time I use Engine=InnoDB in table definition, MariaDB uses XtraDB, eg. code from: `storage/xtradb/handler/ha_innodb.cc`, instead of code from: `storage/innobase/handler/ha_innodb.cc` .

I call cmake in this way:

```
cmake -D CMAKE_INSTALL_PREFIX:STRING=/opt/mariadb-10.2  -D CMAKE_BUILD_TYPE:STRING=Debug  -D CMAKE_CXX_FLAGS_DEBUG:STRING="-g -O0"   -D CMAKE_C_FLAGS_DEBUG:STRING="-g -O0" -D SECURITY_HARDENED:BOOL=FALSE -DWITH_DEBUG=true -D CPLUGIN_TOKUDB:STRING=NO -DWITH_INNOBASE_STORAGE_ENGINE=ON ..
```

2) How to disable some tests, when XtraDB is enabled and vice versa.

**Comment by midenok** [comment]
1) Did you update to 590af2a4fda6e76b12b58b514099af408dcc40df commit? Also, did you rebuild and reinstall properly? Check:

```
grep WITH_INNOBASE_STORAGE_ENGINE CMakeCache.txt
```

I suggest to delete and recreate build directory before running `cmake`.

2) Please, investigate the possibility. Also, please fix if you dicover some incorrect logic from 590af2a4fda6e76b12b58b514099af408dcc40df.

**Comment by avodaniel** [comment]
`grep` printed nothing, but with:

```
-DCWITH_INNOBASE_STORAGE_ENGINE:STRING=ON
```

instead of:

```
-DWITH_INNOBASE_STORAGE_ENGINE=ON
```

`grep WITH_INNOBASE_STORAGE_ENGINE CMakeCache.txt` prints:

```
CWITH_INNOBASE_STORAGE_ENGINE:STRING=ON
```

But still code from `storage/xtradb` is run instead of code from `storage/innobase` .

**Comment by midenok** [comment]
Check this:

```
$ grep '_INNOBASE|_XTRADB' CMakeCache.txt
PLUGIN_INNOBASE:STRING=STATIC
PLUGIN_XTRADB:STRING=DYNAMIC
WITH_INNOBASE_STORAGE_ENGINE:INTERNAL=ON
```

Should be like in the example. What's your output?

**Comment by midenok** [comment]
Also:
```
$ grep -A 7 -n _INNOBASE src/CMakeLists.txt
351:IF(WITH_INNOBASE_STORAGE_ENGINE)
352-  SET(WITH_XTRADB_STORAGE_ENGINE OFF)
353-  IF(PLUGIN_XTRADB STREQUAL STATIC)
354-    SET(PLUGIN_XTRADB DYNAMIC)
355-  ENDIF()
356-ELSE()
357-  SET(WITH_XTRADB_STORAGE_ENGINE ON)
358-ENDIF()
```

**Comment by avodaniel** [comment]
cmake may be the point:

```
$ cmake --version
cmake version 2.8.12.2
```

**Comment by avodaniel** [comment]
Now MariaDB says that InnoDB isn't supported.

```
$ grep '_INNOBASE\|_XTRADB' CMakeCache.txt
CWITH_INNOBASE_STORAGE_ENGINE:STRING=ON
PLUGIN_INNOBASE:STRING=STATIC
PLUGIN_XTRADB:STRING=DYNAMIC
```

I cannot find directory `src`.

**Comment by midenok** [comment]
`src` is my source root. Why **`C`** in `CWITH_INNOBASE_STORAGE_ENGINE`?

**Comment by midenok** [comment]
I think 2.8 requires explicit `CACHE`  clause in [above](https://github.com/natsys/mariadb_10.2/issues/21#issuecomment-249164378). Can you correct the code?

**Comment by midenok** [comment]
I corrected the code and checked on `2.8.7`. Could you please try it now:

```
{hagrid} midenok@lian:build$ cmake ../src; grep -E '_INNOBASE|_XTRADB' CMakeCache.txt
-- Running cmake version 2.8.7
-- MariaDB 10.2.1
-- Packaging as: mariadb-10.2.1-Linux-x86_64
-- checking for one of the modules 'libsystemd;libsystemd-daemon'
-- CMake 2.8.9 or higher is required by TokuDB
-- Configuring done
-- Generating done
-- Build files have been written to: /home/midenok/src/mariadb/hagrid/build
PLUGIN_INNOBASE:STRING=DYNAMIC
PLUGIN_XTRADB:STRING=STATIC
WITH_XTRADB_STORAGE_ENGINE:INTERNAL=ON
{hagrid} midenok@lian:build$ cmake -DWITH_INNOBASE_STORAGE_ENGINE=ON ../src; grep -E '_INNOBASE|_XTRADB' CMakeCache.txt
-- Running cmake version 2.8.7
-- MariaDB 10.2.1
-- Packaging as: mariadb-10.2.1-Linux-x86_64
-- checking for one of the modules 'libsystemd;libsystemd-daemon'
-- CMake 2.8.9 or higher is required by TokuDB
-- Configuring done
-- Generating done
-- Build files have been written to: /home/midenok/src/mariadb/hagrid/build
PLUGIN_INNOBASE:STRING=STATIC
PLUGIN_XTRADB:STRING=DYNAMIC
WITH_INNOBASE_STORAGE_ENGINE:INTERNAL=ON
```

**Comment by midenok** [comment]
Enabled _internal InnoDB only_ in tests.

**Comment by avodaniel** [comment]
Hello. I tested it with both cmake 2.8 and cmake 3.6 and it is working.
