### ISSUE TITLE
Partitioning: creation syntax improvement

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#222]
### 1. remove `as of now` and `versioning` 
In syntax
```sql
create or replace table t1 (x int)
 with system versioning
 partition by system_time limit 1 (
  partition p0 versioning,
  partition p1 versioning,
  partition pn as of now);
```
There is no need in words `as of now` and `versioning` since `as of now` is always single and last partition.

### 2. shortcut syntax
Make shortcut of the above that looks:
```sql
create or replace table t1 (x int)
 with system versioning
 partition by system_time limit 1 partitions 3;
```
The number **3** includes `as of now` partition.

### 3. implied `with system versioning`.
Partitioning **by system_time** should imply `with system versioning` clause for a table.

**Comment by vuvova** [comment]
I'd like this syntax to be as similar visually to existing partitioning syntax as possible.

* `partition by system_time` is good
* `partition by system_time limit 1` is kind of weird, but not completely out of place, `partition by range columns` sets a precedent
* last column is always "as of now" — I don't think we have a precedent for that. If not, I'd prefer explicit "as of now" or "default" (we started to support default partitions recently).
