### ISSUE TITLE
Special privilege and different syntax for TRUNCATE HISTORY

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#229]
## 1. Add specifal privilege level for TRUNCATE
Add `DELETE_VERSIONING_ROWS_ACL` **table**, **db** and **global** levels privilege.

## 2. Syntax change
Current syntax is 
```sql
TRUNCATE [TABLE] t1 FOR SYSTEM_TIME {AS OF|BETWEEN|BEFORE|etc}
```
It should be changed to
```sql
TRUNCATE [TABLE] t1 TO SYSTEM_TIME {/*empty*/|TRANSACTION|TIMESTAMP} xxx;
```
This command truncates history rows with `sys_trx_end` < xxx just as current `BEFORE` does.
## 3. Remove `for system_time before` syntax.

**Comment by midenok** [comment]
What about description?

**Comment by kevgs** [comment]
Failing tests:
`main.system_mysql_db_fix40123 main.system_mysql_db_fix50030 main.system_mysql_db_fix50117`

**Comment by kevgs** [comment]
For `GRANT ALL` to work `DELETE HISTORY` should be also **global** type.
For `GRANT ... ON *.*` to work `DELETE HISTORY` should be also **db** type.

`DELETE` is **table**, **global** and **db** level privilege. It looks like `DELETE HISTORY` should be the same too.

**Comment by kevgs** [comment]
`*.*` also requires adding `Delete_history_priv` to `mysql.user` table.
