### ISSUE TITLE
drop system versioning clause

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#268]
Described in standard in `11.30 <drop system versioning clause>`: `Change a system-versioned table into a regular persistent base table`.

**Comment by kevgs** [comment]
Already implemented.

**Comment by midenok** [comment]
Commit reference?

**Comment by kevgs** [comment]
https://github.com/tempesta-tech/mariadb/commit/f9b8c908a0abbee756f2ef0b100dd9d173bc3e97
