### ISSUE TITLE
0.4: Audit plugin that logs IB transaction boundaries

### ISSUE THREAD

**Issue by avodaniel** [tempesta-tech/mariadb#28]
... audit plugin will know transaction boundaries, it can record (in the audit log) what user started what transaction (what transaction id) and when ...

**Comment by hagrid-the-developer** [comment]
What is the funtion of this plugin? Is it something that will print TRX_ID to the logs? Or something that will allow to ask for TRX_ID in select statements, like:

    SELECT TRX_ID FROM t ...

?

**Comment by hagrid-the-developer** [comment]
It seems that this plugin should be extended: https://mariadb.com/kb/en/mariadb/about-the-mariadb-audit-plugin/ . Its sources are in `plugin/server_audit/` .

**Comment by krizhanovsky** [comment]
I'm just copying @vuvova's reply here:

> If audit plugin will know transaction boundaries, it can record
> (in the audit log) what user started what transaction (what transaction
> id) and when. Which will allow later - using "AS OF TRANSACTION id" -
> to see what data was visible to that user.
> 
> Without an audit log with transaction ids, there is no place to take the
> argument for "AS OF TRANSACTION id" from. So, the specs basically said
> that "AS OF TRANSACTION id" won't have much sense without the audit log
> with transaction ids, and you could've spend your time on something more
> useful instead.
> 
> As for now, I see following options:
> 1. all the above is still true, you skip AS OF TRANSACTION, postpone it
>    until audit plugin is ready
> 2. you have (or you create) some other source of transaction ids
>    and then implement AS OF TRANSACTION
> 3, you implement AS OF TRANSACTION without any good source of
>    transaction ids - the feature will exist, but won't be much used
>    until audit plugin catches up.

**Comment by kevgs** [comment]
[This](https://github.com/natsys/mariadb_10.2/blob/natsys/trunk/sql/sql_audit.h#L89) function already logs user and time. It looks like a proper place to log trx_id too.
