### ISSUE TITLE
IB inplace alter

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#290]
### `alter.test` fails
Following commit is affected:
```
commit fb801289f314bee6e5b1864f3ef58f8f38a59278
Author: kevg <claprix@yandex.ru>
Date:   Fri Feb 17 15:11:15 2017 +0300

    IB, Tests: ALTER with ALGORITHM=INPLACE for InnoDB [closes #87]

```

**Comment by kevgs** [comment]
MDEV-11369 Instant ADD COLUMN for InnoDB
Related to this new feature https://github.com/MariaDB/server/commit/a4948dafcd7eee65f16d848bdc6562fc49ef8916
