### ISSUE TITLE
Revisit formatting, numeric types

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#306]
1. Replace `ullong` and `ulonglong` with `uint64_t` or some typedef alias, say, `timestamp_t` or `trx_id_t`. Try to remove all added references to the `long` or `ulong` data types. We need a portable 64-bit type for the timestamps and transaction identifiers.

2. Fix [review comments](https://github.com/MariaDB/server/pull/478) on formatting.

**Comment by kevgs** [comment]
`int64_t` is not available for `sql`. `int64` is available instead but these 2 types are different: `type mismatch at 3rd parameter ('uint64' (aka 'unsigned long long') vs 'uint64_t' (aka 'unsigned long'))`
