### ISSUE TITLE
Organize nightly builds

### ISSUE THREAD

**Issue by avodaniel** [tempesta-tech/mariadb#31]
Install and run BuildBot on mariadb-testbed

**Comment by kevgs** [comment]
Would not it be easier to set up Travis CI?

**Comment by midenok** [comment]
Basic info on [Travis CI](https://en.wikipedia.org/wiki/Travis_CI) seems to be favourable. Worth to try.

**Comment by kevgs** [comment]
Here is how it looks:
https://travis-ci.org/kevgs/mariadb_10.2
https://github.com/kevgs/mariadb_10.2/blob/natsys/trunk/.travis.yml
Triggers on every commit or PR (before merging)

Is it all we need or BuildBot have some killer feature?

**Comment by kevgs** [comment]
Added CI to natsys/trunk. It runs just a few tests (complete list is here https://github.com/natsys/mariadb_10.2/blob/natsys/trunk/.travis.yml)

Here is a page with current build status: https://travis-ci.org/natsys/mariadb_10.2

I suggest to use for some time and decide what to do with it next (remove of add more tests/build configurations).

**Comment by midenok** [comment]
1. How it will report failed tests?
2. It needs to build debug version as well (`-O0 -g`), so that stack traces were readable. Also `-D SECURITY_HARDENED:BOOL=FALSE` may influence something.
3. Why `-j 3`? Is it limit for CPUs on free account? I would suggest `-j 8` if there is no limit.

**Comment by kevgs** [comment]
1. Right now it sends me emails. But it's configurable. The most useful IMO is a fancy labels at the top of README.md like [here](https://github.com/rubinius/rubinius). But this particular feature requires to rename README to README.md. Is such renaming is acceptable for us?
2. I will answer this a bit later.
3. I don't know about restrictions of a VM. -j3 is just a random setting. I can change this to -j8 because I have nothing against it. It could be better and I won't be worse.

**Comment by midenok** [comment]
Ok. Can it differ build phase and test phase, so that it were clear whether build or tests have failed? Also it would be useful to do only builds for every commit and do tests nightly.

**Comment by kevgs** [comment]
The icon always use word 'build'. But if you'll see logs you can easily understand what exactly failed.

**Comment by midenok** [comment]
It's not very convenient. It would be better if there are 2 different icons.

**Comment by kevgs** [comment]
On the other hand it encourages to make commits which doesn't brake both build and tests.

**Comment by kevgs** [comment]
1. I didn't find out how to test both Debug and Release configurations and chose Debug -DSECURITY_HARDENED=1 also because it has assertions.

Travis VM have 2 cores, so -j2 is the best we can do.

**Comment by kevgs** [comment]
Also renamed README -> README.md to show a fancy icon on the main repo page.

**Comment by midenok** [comment]
> Travis VM have 2 cores, so -j2 is the best we can do.

Probably, `-j $(grep -c processor /proc/cpuinfo)` can do the job.

> On the other hand it encourages to make commits which doesn't brake both build and tests.

The question is not in psychology. There are periods like the current one, when tests fail. This is usual property of trunk, tests are guaranteed only in release branches. In such periods status icon will be unusable.

Can it schedule not by commit, but by time (e.g. nightly)?

Now it shows [some strange errors](https://travis-ci.org/natsys/mariadb_10.2/builds/165309581). Why it started to build my branch if there is no `.travis.yml`?

**Comment by midenok** [comment]
Anyway, the main topic is _nightly_, i.e. _one_ time per day. The full test suite runs for 6-8 hours. If it will run on each commit -- this will be totally unusable. Per commit build check and several tests is nice feature, but not a big deal.

**Comment by kevgs** [comment]
It is possible to build once a day. But I need to find out how to bypass internal time limit on a build run.

**Comment by midenok** [comment]
Maybe it is possible only in paid version.

**Comment by krizhanovsky** [comment]
We can purchase the paid version, but do we need this?

**Comment by midenok** [comment]
Not at all, if we can make same thing with cron job at test-bed.

**Comment by midenok** [comment]
Migrated to #62
