### ISSUE TITLE
Misc: C++11 protectors for C variadic functions

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#325]
Related to #307 (garbage error argument)

Functions like `my_error()`, `push_warning_printf()` should be wrapped by a type checker. In case when non-plain type was put as an argument to such function, C++11 compiler will fail with error.

[This answer](https://stackoverflow.com/a/7232968/3824341) has good example to start:
```c++
#include <vector>
#include <iostream>

struct any {
  enum type {Int, Float, String};
  any(int   e) { m_data.INT    = e; m_type = Int;}
  any(float e) { m_data.FLOAT  = e; m_type = Float;}
  any(char* e) { m_data.STRING = e; m_type = String;}
  type get_type() const { return m_type; }
  int get_int() const { return m_data.INT; }
  float get_float() const { return m_data.FLOAT; }
  char* get_string() const { return m_data.STRING; }
private:
  type m_type;
  union {
    int   INT;
    float FLOAT;
    char *STRING;
  } m_data;
};

template <class ...Args>
void foo_imp(const Args&... args)
{
    std::vector<any> vec = {args...};
    for (unsigned i = 0; i < vec.size(); ++i) {
        switch (vec[i].get_type()) {
            case any::Int: std::cout << vec[i].get_int() << '\n'; break;
            case any::Float: std::cout << vec[i].get_float() << '\n'; break;
            case any::String: std::cout << vec[i].get_string() << '\n'; break;
        }
    }
}

template <class ...Args>
void foo(Args... args)
{
    foo_imp(any(args)...);  //pass each arg to any constructor, and call foo_imp with resulting any objects
}

int main()
{
    char s[] = "Hello";
    foo(1, 3.4f, s);
}
```

C++ [compiler version](http://www.stroustrup.com/C++11FAQ.html#11) can be checked like this:
```c++
#if __cplusplus > 199711L
  // C++11 code
#endif
```

**Comment by FooBarrior** [comment]
I'd prefer it to be completely a build-time feature. It implies parsing format string at compile time. There are some pure c++ solutions, one example is [Boost.Hana](https://www.boost.org/doc/libs/1_68_0/libs/hana/doc/html/index.html)

But the drawback (behind that boost will doubtly be enabled in maria) is that any failure might produce kilometers of errors.
