### ISSUE TITLE
versioning plugin is not loaded

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#332]
[kvm-deb-trusty-amd64](http://buildbot.askmonty.org/buildbot/builders/kvm-deb-trusty-amd64/builds/8276/steps/mtr/logs/stdio) fails with following error:
```
2017-11-20 18:46:33 0 [ERROR] Couldn't load plugins from 'versioning.so'.
```

**Comment by kevgs** [comment]
`.deb` package isn't created. That's the problem.
