### ISSUE TITLE
Reliability and performance tests

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/mariadb#34]
Following to discussion with Alvin we need to solve how to test reliability and performance of the feature. It's clear that `sysbench` or `dbt2` workloads running on our VPS testbed aren't enough to guarantee stability in real life installations working on large multi-core systems with extremely long uptime. Need to discuss the issue with MariaDB QA team.

**Comment by midenok** [comment]
@krizhanovsky, please provide contact of QA team.

**Comment by krizhanovsky** [comment]
How to do the tests is still discussed, I'll back when I have something. I think we won't get something until end of October, 0.4 release.

**Comment by krizhanovsky** [comment]
As discussed with Elena Stepanova, MariaDB has extensive suite for stress tests including fuzzing test, so the tests will be done on MariaDB's side after merge with 10.3.
