### ISSUE TITLE
Implicitly created fields (according to spec) must also become hidden.

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#38]
CREATE TABLE t (
a INT
) WITH SYSTEM VERSIONING;

SHOW CREATE TABLE t;

CREATE TABLE `t1` (
  `a` int(10) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 WITH SYSTEM VERSIONING

**Comment by midenok** [comment]
[06-Oct-16 19:46:40] Daniel Fiala: Aleksey, Eugene, issue #38 (Implicitly created fields must also become hidden) will be probably covered by MariaDB.
[06-Oct-16 20:28:17] Eugene Kosov: Here is a ticket https://jira.mariadb.org/browse/MDEV-10177 and here is the set of patches to fix that ticket https://github.com/MariaDB/server/compare/10.2...SachinSetiya:unique_index_sachin and they-re not commited.

Do we have to depend on such huge feature? There are not much work to hide our columns:
- fix `show.cc` like in branch from above;
- fix `setup_wild()` to skip our fields from being expanded in `SELECT *`;
- what else?

**Comment by avodaniel** [comment]
I also need to hide fields in #32, so we need to sync somehow. I will also need to hide other fields, like `WITH SYSTEM VERSIONING`.

**Comment by midenok** [comment]
There are different conditions. I believe there is no need to sync until conflict resolution on merge.

**Comment by avodaniel** [comment]
There are different conditions but probably similar actions. So we would have same thing (hiding of columns) implemented for three times.

**Comment by midenok** [comment]
Skipping is not _action_ it's _condition_. Just add condition to skip your fields in list iteration loop. What else is required to be implemeted for three times?

**Comment by kevgs** [comment]
Initial assumption on incorrect SHOW CREATE TABLE was wrong. Actually we have 2 tasks:
- [ ] hide sys_trx_begin/sys_trx_end from `SELECT *` (done https://github.com/natsys/mariadb_10.2/commit/d2f2f558f8422bf0de9522d5bc2e5d438255d16f)
- [ ] hide sys_trx_begin/sys_trx_end from DESCRIBE

**Comment by midenok** [comment]
Hide **only implicit** fields from `SELECT *`. Don't hide from DESCRIBE and `SHOW CREATE TABLE`.

**Comment by kevgs** [comment]
Can we consider this issue resolved due to https://github.com/natsys/mariadb_10.2/commit/302fdbe88087b8827b01820f262286cc526dd3f9 ?

Also, it looks like there is no need in porting code from here https://github.com/MariaDB/server/compare/10.2...SachinSetiya:unique_index_sachin, right?
