### ISSUE TITLE
Truncate history of partitioned table

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/mariadb#403]
Commit https://github.com/tempesta-tech/mariadb/commit/ab5ec0f346a8244e99067fab0fbd6b48f23cee9c just disables attempt to truncate history in a partitioned table. Need to implement the feature.

Please update reference to the issue in https://github.com/tempesta-tech/mariadb/wiki/High-level-design#history-purging when it's done.

**Comment by midenok** [comment]
As per comment from @vuvova removing empty partitions is not the part of TRUNCATE. Therefore functionality is not different from truncate of non-partitioned table.

**Comment by midenok** [comment]
Depends on #399.
