### ISSUE TITLE
History table as separate table

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#412]
Make syntax that will optionally allow to choose separate history table.

From [chat](https://tempesta-tech.slack.com/archives/C80AX4708/p1513363858000354):
> [21:50] serg (@vuvova): the big benefit of a separate table, one can have different indexes on it

Drawback of history inside table is that it requires **sys_trx_end** to be added to PK which triggers index rebuild each time record is deleted.

**Comment by kevgs** [comment]
`row_start/row_end` is prohibited inside `UNIQUE|PRIMARY KEY` by standard in `11.7 <unique constraint definition>`. Constrains should be evaluated for `t for system_time as of current_timestamp`.
