### ISSUE TITLE
GENERATED ALWAYS are mandatory keywords

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#418]
```
11.4 <column definition>
...
<system time period start column specification> ::=
<timestamp generation rule> AS ROW START

<system time period end column specification> ::=
<timestamp generation rule> AS ROW END

<timestamp generation rule> ::=
GENERATED ALWAYS
```

We have not this:
```c++
opt_generated_always AS ROW_SYM start_or_end opt_asrow_attribute
```

**Comment by midenok** [comment]
From [chat](https://tempesta-tech.slack.com/archives/C80AX4708/p1513603647000156):
> [16:27] 
midenok @vuvova One more question about `GENERATED ALWAYS`. Can we keep it optional as now and imply it by default? Standard doesn't mention it optional but I think it may be defect.
[16:28] 
serg you mean `col TIMESTAMP(6) AS ROW START` ?
[16:28] 
midenok Yes
[16:29] 
serg good point, should be optional, like for any other generated columns.
[16:30] 
they're _just_ generated columns with normal generated-column behavior in most cases
[16:30] 
@midenok I suppose if you use existing grammar for generated columns, you'll get `GENERATED ALWAYS` optional automatically
[16:34] 
midenok Sure. That was just double-check question.
