### ISSUE TITLE
Hide system versioning fields in SHOW CREATE VIEW

### ISSUE THREAD

**Issue by avodaniel** [tempesta-tech/mariadb#42]
When creating VIEW from system versioning table, clauses that are used to do versioned search  over the table are added to WHERE part of the statement and are printed eg. by `SHOW CREATE VIEW ...` .

They should be probably hidden if hiding of System Versioned fields is enabled. Maybe `VIEW` should be created without these fields in `WHERE`. Also, user can add some conditions related to `Sys_start` or `Sys_end` to where clause and then they should be printed.

**Comment by midenok** [comment]
No need to modify `SHOW CREATE VIEW` since `insert_fields()` hides fields from `SELECT`.
