### ISSUE TITLE
RBR-SBR replication conversion for timestamp-based InnoDB system versioning

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/mariadb#448]
Previously we silently converted RBR asynchronous replication to SBR for InnoDB tables with system versioning, however, after #416 was merged, by default InnoDB system versioning uses timestamp based versioning. Thus, the asynchronous replication types conversion is required only for InnoDB transaction ID system versioning.

**Comment by kevgs** [comment]
Actually, it works as it should:
https://github.com/tempesta-tech/mariadb/blob/3eccdba2d510dc9511dfdfab8d9a462e78386533/sql/sql_insert.cc#L1149
https://github.com/tempesta-tech/mariadb/blob/3eccdba2d510dc9511dfdfab8d9a462e78386533/sql/sql_update.cc#L1118
https://github.com/tempesta-tech/mariadb/blob/3eccdba2d510dc9511dfdfab8d9a462e78386533/sql/sql_delete.cc#L843

This code switches to SBR only for trx_id based tables (currently InnoDB only).
