### ISSUE TITLE
DESCRIBE for versioned tables

### ISSUE THREAD

**Issue by kevgs** [tempesta-tech/mariadb#49]
GENERATED AS ROW START/END fields must not be shown to user.

**Comment by midenok** [comment]
Why do you want to hide DESCRIBE and don't hide SHOW CREATE TABLE? I think it should be vice versa: SHOW CREATE TABLE shows exact command which created table, so fields should be hidden. DESCRIBE should not hide fields to inform user of real state of things.

**Comment by kevgs** [comment]
SHOW CREATE TABLE doesn't show exact command which created table so this argument is not strong. See:

```
CREATE TABLE t1(
A INT
);
```

```
CREATE TABLE `t1` (
  `A` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1
```

User should be able to query sys_trx_start/sys_trx_end so he need some way to see it either on SHOW CREATE TABLE or DESCRIBE.

It's easy to hide it from SHOW CREATE TABLE. It requires just adding a new flag (like HIDE_IMPLICIT_VERSIONNG_FIELDS_FLAG) to table in .frm. Add it to EXTRA2 because we have no other suitable place (or at least I don't know the other one).

It's difficult to hide it from DESCRIBE because it's a SELECT to INFORMATION_SCHEMA internally and right now it's impossible to get suitable info with that SELECT. Overall making this work requires a lot of work.

Here is what I think.

sys_trx_begin/sys_trx_end and it's actual type is an implementation details. And user should not see these implementation details at all because they may change in future. Instead it would be useful to restrict access to these fields at all: disallow specifying it at CREATE TABLE (just use WITH/WITHOUT SYSTEM VERSIONING on fields and whole table) and provide two functions ROW_START_TS(), ROW_END_TS() and ROW_START_TRX() and ROW_END_TRX() for InnoDB tables. User will have the same functionality but without a mess in SHOW CREATE_TABLE, DESCRIBE and SELECT *.

This requires to hide versioning fields from everything which is not easy overall.

What do you think?

**Comment by kevgs** [comment]
Btw, https://jira.mariadb.org/browse/MDEV-10177 hides columns from SELECT \* only and not requires them in INSERT. Which is done ad-hoc already.

**Comment by midenok** [comment]
No, I think it have no practical use. It is convenient to see these fields for historical tables. Maybe there is no need to hide them neither in SHOW CREATE nor in DESCRIBE at all (again, no practical use). I would add explicit HIDDEN clause to hide these fields. And for implicit fields this clause should be added implicitly, so we are waiting update on this feature. User should be able to switch HIDDEN property with ALTER TABLE any time.
