### ISSUE TITLE
mark_columns_needed_for_update() algorithm cleanup

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#550]
In this code of `mark_columns_needed_for_update()` if `use_all_columns()` is called there is no need to call other `mark_` functions. I guess that even `mark_column_with_deps()` is not needed. So we have to check `(s->versioned || with_period)` as early as possible and exit func immediately. Don't forget about `need_signal`. Currently not setting it is a possible bug.

```c++
  /*
     For System Versioning we have to read all columns since we will store
     a copy of previous row with modified Sys_end column back to a table.
     The same applies to Application-time period tables.
  */
  if (s->versioned || with_period)
  {
    // We will copy old columns to a new row.
    use_all_columns();
  }
  if (check_constraints)
  {
    mark_check_constraint_columns_for_read();
    need_signal= true;
  }
```

**Comment by FooBarrior** [comment]
BTW calling `use_all_columns` makes `row_format=MINIMAL` to replicate a full row. Maybe we can mark columns just before versioned insert, and then restore the mark state?
