### ISSUE TITLE
Application periods: wrong dates allowed

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#566]
### Reproduce
```sql
create or replace table p1(x int, s datetime, e datetime, period for p(s, e));
insert into p1 values (1, '2000-00-01 00:00', '2010-00-00 00:00');
```
### Result
No error.
### Expected
INSERT failed with error.
### Info
Related to **[MDEV-17798 System variable system_versioning_asof accepts wrong values](https://jira.mariadb.org/browse/MDEV-17798)**.

**Comment by FooBarrior** [comment]
How is this related to periods?
