### ISSUE TITLE
Scripts: collect and reprint warnings at build finish

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#73]
Use [following](http://stackoverflow.com/questions/31348508/save-and-reprint-warnings-for-successfully-compiled-files-on-subsequent-builds) technique to reprint warnings.

* do this only for Debug build;
* make it work without any external scripts (like `build.sh` in answer);
* review code in `capture_warnings.sh.in` and fix wrong points:
    - no need to generate `remove_obj_with_warnings.sh`;
    - no need to output per-object `.warnings` files, there should be one single file in top build dir: `compile.warnings`;
    - `make clean` removes `compile.warnings`.

**Comment by kevgs** [comment]
Ninja outputs both current file info and gcc warnings at stdout.
Make outputs current file info to stdin and gcc warnings to stdout.

So it's possible to use something like `make 2> /tmp/warnings && cat /tmp/warnings`
In that case warning will not be printed just after some file compiles but instead all warnings will be printed when compilation finished.

**Comment by kevgs** [comment]
And this one does everything what plain `make` does but also outputs warnings to a separate file. But this do not work with `-j4`.

``` bash
make 3>&1 1>&2 2>&3 | tee /tmp/warnings && cat /tmp/warnings
```

**Comment by midenok** [comment]
We all know how to use shell. Just make what description says.

**Comment by kevgs** [comment]
- [x] Collect all warnings to compile.warnings file using additional bash script (without copying it to build directory).
- [ ] Reprint all warnings at the end of project build.
- [x] Remove `compile.warnings` at every project build (runs at random time).
- [x] `make clean` deletes `compile.warnings`.
- [ ] Work with --jobs > 1

**Comment by kevgs** [comment]
Complications with warnings reprint: it seems there is no way to run something after all other targets. http://stackoverflow.com/questions/30532448/what-is-the-name-of-cmakes-default-build-target
Possible workaround: make reprint depend on some late target like linking mysqld.

**Comment by midenok** [comment]
Did you look at `Makefile`?

``` make
all: cmake_check_build_system
        $(CMAKE_COMMAND) -E cmake_progress_start /home/midenok/src/mariadb/midenok/build/CMakeFiles /home/midenok/src/mariadb/midenok/build/CMakeFiles/progress.marks
        $(MAKE) -f CMakeFiles/Makefile2 all
        $(CMAKE_COMMAND) -E cmake_progress_start /home/midenok/src/mariadb/midenok/build/CMakeFiles 0
.PHONY : all
```

```
$ grep '^all:' Makefile2|tail
all: sql/CMakeFiles/udf_example.dir/all
all: sql/CMakeFiles/sql.dir/all
all: sql/CMakeFiles/partition.dir/all
all: sql/CMakeFiles/mysql_tzinfo_to_sql.dir/all
all: sql/CMakeFiles/gen_lex_token.dir/all
all: sql/CMakeFiles/gen_lex_hash.dir/all
all: wsrep/CMakeFiles/wsrep.dir/all
all: mysql-test/lib/My/SafeProcess/CMakeFiles/my_safe_process.dir/all
all: scripts/CMakeFiles/GenFixPrivs.dir/all
all: scripts/CMakeFiles/comp_sql.dir/all
```

Make your `all:` target appear in Makefile2 in the end. Add `ALL` target at end of CMakeLists.txt

**Comment by midenok** [comment]
From CMake [manual](https://cmake.org/cmake/help/v3.0/command/add_custom_command.html):

```
PRE_BUILD - run before all other dependencies
PRE_LINK - run after other dependencies
POST_BUILD - run after the target has been built
```

**Comment by kevgs** [comment]
``` cmake
ADD_CUSTOM_TARGET(ALL
  ALL
  COMMAND echo "reprinting")
```

Here is a custom target named ALL to ./CMakeLists.txt. It works, but it has no dependencies. I need it to work after building all other targets, because without dependencies it's built just after `make`. And some guy in a link to Stackoverflow above said it's impossible to create a target which depends on everything.

``` cmake
ADD_CUSTOM_COMMAND(TARGET
  ALL
  POST_BUILD
  COMMAND echo "post build everything")
```

Here I create a custom command and associate it with my custom target. I say it to work just after my target is built. And it works like this:

```
[  0%] Built target abi_check
[  0%] Built target ResetCapturedWarnings
[  0%] Built target INFO_BIN
[  0%] Built target INFO_SRC
reprinting
post build everything
[  0%] Built target ALL
[  0%] Building C object unittest/mytap/CMakeFiles/mytap.dir/tap.c.o
[  0%] Linking C static library libmytap.a
[  0%] Built target mytap
```

Here is a workaround. I add some to ./sql/CMakeLists.txt

``` cmake
ADD_CUSTOM_TARGET(AFTER_MYSQLD
  ALL
  COMMAND echo "reprinting after mysqld"
  DEPENDS mysqld)
ADD_CUSTOM_COMMAND(TARGET
  AFTER_MYSQLD
  POST_BUILD
  COMMAND echo "post build everything after mysqld")
```

```
[100%] Built target mysql_client_test
Scanning dependencies of target mysqld
[100%] Building CXX object sql/CMakeFiles/mysqld.dir/main.cc.o
[100%] Linking CXX executable mysqld
[100%] Built target mysqld
Scanning dependencies of target AFTER_MYSQLD
reprinting after mysqld
post build everything after mysqld
[100%] Built target AFTER_MYSQLD
Scanning dependencies of target udf_example
```

Am I missed something from what you said?

**Comment by midenok** [comment]
Can't you just:

``` cmake
ADD_CUSTOM_COMMAND(TARGET
  mysqld
  POST_BUILD
  COMMAND echo "post build everything after mysqld")
```

?

**Comment by midenok** [comment]
This works in top-level CMakeLists.txt:

``` diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6c7899c..cda299b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -476,6 +476,11 @@ ENDIF()

 INCLUDE(CPack)

+ADD_CUSTOM_TARGET(SOME_TARGET ALL
+  COMMAND echo "reprinting"
+  DEPENDS mysqld
+)
+
 IF(NON_DISTRIBUTABLE_WARNING)
   MESSAGE(WARNING "
 You have linked MariaDB with GPLv3 libraries!  You may not distribute the resulting binary. If you do, you will put yourself into a legal problem with Free Software Foundation.")
```
