### ISSUE TITLE
Maintenance of SYSTEM_TIME history

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#82]
There should be following abilities to handle SYSTEM_TIME history:

* copy table *as is* with the full history (now the following command creates unversioned table: `create table t2 select * from t1 for system_time all`);
* delete all history or portion of early history;
* delete portion of late history and live data;
* split history to partitions by periods of time or by record count.

**Comment by alvinr** [comment]
There seems at least three ways to copy this history
* `create table .. select ... for system_time all` (as you mention above)
* `replace into ... select ... for system_time all`
* `insert into ... select ... for system_time all`

**Comment by kevgs** [comment]
It's good to have some way to remove a data from `VTQ` AND `VTD` system tables. Possibly via `TRUNCATE FOR SYSTEM_TIME`. Note, that `VTQ` contains data from different tables and doing a simple `DELETE FROM VTQ WHERE sys_trx_end<SOME_TRX_ID` is not an option.

**Comment by kevgs** [comment]
One possible feature is to add more info about system versioning to `EXPLAIN SELECT`. E.g. show user somehow that his query will read/write to `VTQ` or to show which set of historical tables we're going to read.
