### ISSUE TITLE
Postpone or renounce versioned DDL feature

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#83]
Due to complex logic especially in case of `select * from t1 for system_time all` and doubtful advantages propose to renounce *versioned DDL* or postpone to 2.0 until feedback from users. 

Instead of *versioned DDL* propose to add 3 modes of ALTER TABLE:
1. if history is influenced (like when dropping a field), extract history to a separate table;
2. do nothing special about history (the table will contain modified history).
3. combine 1. and 2.

**Comment by midenok** [comment]
Even when the command is `select * from t1 for system_time as of {time}`, the fact that SELECT from same table produces different field sets (for different points of *time*) makes the feature doubtful. It complicates not only server code, but also client code to support such functionality.

**Comment by kevgs** [comment]
**Current status.**

ALTER works, but it works on a single table. On column ADD/DROP/MODIFY history get lost both in InnoDB and other engines. So, it works as in 2. item of an initial post here.

Note on InnoDB. It implements ALTER queries internally (instead of in SQL level). And it implements both `INPLACE` and `COPY` algorithms. These queries do not work and temporarily disallowed and should be implemented in future.
```sql
ALTER TABLE t WITH SYSTEM VERSIONING, ALGORITHM=INPLACE;
ALTER TABLE t WITHOUT SYSTEM VERSIONING, ALGORITHM=INPLACE;
```

**Comment by midenok** [comment]
This is not the subject of current issue.

**Comment by midenok** [comment]
Created e-mail thread and [wiki page](https://github.com/natsys/mariadb_10.2/wiki/Versioned-DDL-cons).

**Comment by krizhanovsky** [comment]
I believe the Wiki page is wrong. Alvin clearly described use cases for DDL survival. You also can learn cases from Oracle and Microsoft documentation referenced in our HLD. Moreover, usual client should not be aware about the feature, everything can be handled at database server and only special (e.g. forensic discovering client) should be aware about the feature. So please remove the Wiki.
