### ISSUE TITLE
0.6: History truncation

### ISSUE THREAD

**Issue by midenok** [tempesta-tech/mariadb#96]
As described in **FLEXIBLE HISTORY PURGING** in HLD.

       > TRUNCATE TABLE employee FOR SYSTEM_TIME TRANSACTION BETWEEN 10000 AND 20000;
       > TRUNCATE TABLE employee FOR SYSTEM_TIME AS OF TIMESTAMP '2016-02-06 10:03:03';

**Comment by midenok** [comment]
Looks like 1-week task. Please, estimate.

**Comment by kevgs** [comment]
**Feature design:**

Ordinary DELETE does not see history rows:
```sql
DELETE FROM t;
```

History DELETE sees history rows only:
```sql
DELETE FROM t HISTORY;
```

**Comment by midenok** [comment]
Look how DELETE works and do the same thing or just translate TRUNCATE command to DELETE.

### Optimization
If WHERE condition covers whole VERSIONING partition, just do DROP PARTITION.

**Comment by kevgs** [comment]
So, it's just DELETE which sees historical fields. Then, what about syntax like `DELETE FROM t WITH SYSTEM VERSIONING WHERE ...` ?

If it's DELETE how do we add TRX_ID/TIMESTAMP keywords to standard expression parser? If we change expression syntax how do we disallow it to every type of query but this one? Maybe it's better just to use sys_trx_start/sys_trx_end?

What do you think?

**Comment by midenok** [comment]
Just use `opt_for_system_time_clause`. I corrected **description** accordingly. Don't add ALTER command, Make only TRUNCATE TABLE.
