### ISSUE TITLE
0.7: "AS OF" query for VIEW

### ISSUE THREAD

**Issue by alvinr** [tempesta-tech/mariadb#98]
# Problem
You cannot perform an "As Of" query through a view definition based on a Versioned table, you get the following error

```
ERROR 4031 (HY000): System Versioning required: `FOR SYSTEM_TIME` query
```

# Solution
A view can be a restricted projection of data, joins etc. on the underlying tables & views. If you add a predicate to a query with a view, then this is simply added to the overall query predicate. It would seem that "As Of" would behave in the same way, a further restriction to the underlying query.

The spec does not seem to call out any explicit behavior for views.

# Reproduce
```
create or replace table dept (
  dept_id int(10) primary key, 
  name varchar(100)
)
with system versioning
;

insert into dept (dept_id, name) values (10, "sales");

select vtq_commit_ts(sys_trx_start) into @ts_1 from dept where dept_id=10;

create view dept_view as select * from dept where name = "sales";

select * from dept_view;

select * from dept for system_time as of timestamp @ts_1;

select * from dept_view where dept_id = 10;
+---------+-------+
| dept_id | name  |
+---------+-------+
|      10 | sales |
+---------+-------+

select * from dept_view for system_time as of timestamp @ts_1;
ERROR 4031 (HY000): System Versioning required: `FOR SYSTEM_TIME` query
```

**Comment by midenok** [comment]
This issue is syntax extension and is related to #74.

**Comment by alvinr** [comment]
One additional use case that we needs to be considered

```
create view emp_history
as
select * from emp
for system_time all;
```

The enables the creation of a view which projects the history of the data. In theory you can then apply a `for system_time` constraint to a query against this view

```
select * from emp_history for system_time as of timestamp @ts_basic_2;
ERROR 4031 (HY000): System Versioning required: `FOR SYSTEM_TIME` query
```

This is supported by SQL Server 2016, see https://msdn.microsoft.com/en-us/library/mt631669.aspx

**Comment by midenok** [comment]
Yes, I thought about this possibility. How it is expected to behave: (1) replace inner *system_time* condition, (2) unite or (3) intersect with it?

### Dictionary
#### inner condition
Condition defined in `CREATE VIEW`.

#### outer condition
Condition specified in `SELECT`.

**Comment by midenok** [comment]
@alvinr Please, clarify.

**Comment by alvinr** [comment]
@midenok just found all github updates were going to junk mail - sorry about the delay.

I want to think this through a little further, given the changes in 0.6 where the `for system_time` clause is now on the `from` for each table.

If we have the session level time specified (see https://github.com/natsys/mariadb_10.2/issues/117), then you could do something like

```
SET STATEMENT temporal_current_timestamp =all select * from my_view;
```

Without that feature, it would mean applying the the outer condition on the inner condition - that's not trivial.

Suggest we put this is the backlog for now.

**Comment by kevgs** [comment]
```c++
#0  st_select_lex::add_table_to_list (this=0x7fffe0004d38, thd=0x7fffe0000b00, table=0x7fffe0012ce8, alias=0x7fffe0012d18, table_options=0, lock_type=TL_READ_DEFAULT, mdl_type=MDL_SHARED_READ, 
    index_hints_arg=0x0, partition_names=0x0, option=0x0) at /home/kevg/work/mariadb_10.2/sql/sql_parse.cc:7994
#1  0x00000000009554fd in MYSQLparse (thd=0x7fffe0000b00) at /home/kevg/work/mariadb_10.2/sql/sql_yacc.yy:11236
#2  0x00000000006fa0bf in parse_sql (thd=0x7fffe0000b00, parser_state=0x7ffff09ca168, creation_ctx=0x0, do_pfs_digest=true) at /home/kevg/work/mariadb_10.2/sql/sql_parse.cc:9858
#3  0x00000000006e483b in mysql_parse (thd=0x7fffe0000b00, rawbuf=0x7fffe0012478 "create view vt as select * from t  query for system_time all", length=60, parser_state=0x7ffff09ca168, is_com_multi=false, 
    is_next_command=false) at /home/kevg/work/mariadb_10.2/sql/sql_parse.cc:7801
#4  0x00000000006dfb12 in dispatch_command (command=COM_QUERY, thd=0x7fffe0000b00, packet=0x7fffe0008831 "create view vt as select * from t  query for system_time all", packet_length=60, is_com_multi=false, 
    is_next_command=false) at /home/kevg/work/mariadb_10.2/sql/sql_parse.cc:1798
#5  0x00000000006e31fa in do_command (thd=0x7fffe0000b00) at /home/kevg/work/mariadb_10.2/sql/sql_parse.cc:1358
#6  0x000000000086cda1 in do_handle_one_connection (connect=0x27ce850) at /home/kevg/work/mariadb_10.2/sql/sql_connect.cc:1354
#7  0x000000000086cb7a in handle_one_connection (arg=0x27ce850) at /home/kevg/work/mariadb_10.2/sql/sql_connect.cc:1260
#8  0x000000000125c3c4 in pfs_spawn_thread (arg=0x2718640) at /home/kevg/work/mariadb_10.2/storage/perfschema/pfs.cc:1862
#9  0x00007ffff79bd6ca in start_thread (arg=0x7ffff09cc300) at pthread_create.c:333
#10 0x00007ffff678a0af in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
(gdb) p *alias
$1 = LEX_STRING 0x7fffe0012d10 "query" length 5
```

Looks like a parse error: this table should not have `query` alias.
